# This is a basic workflow to help you get started with Actions

name: Sample running finder.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: set up php
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: install composer packages
      run: composer install

    - name: running phpstan
      env:
      run: ./bin/function-finder -c config.yaml


